version: '3'


services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    command: sh -c "python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - './backend/:/backend/'
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    env_file:
        - ./.env
    volumes:
      - mongodbdata:/data/db
    ports:
    - "27017:27017"

  frontend:
    tty: true
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - './frontend/:/frontend/'
      - '/frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=true


volumes:
    mongodbdata:
        driver: local