version: '3'


services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    command: sh -c "cd src/ && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - mongodb
  nginx:
    build: ./backend/nginx
    # Mapping Container PORT 80 to Host PORT 5000
    ports:
      - 8000:80 
    depends_on:
      - backend
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    env_file:
        - ./backend/.env
    volumes:
      - mongodbdata:/data/db
    ports:
    - "27017:27017"
  frontend:
    container_name: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile.prod
    ports:
      - '3000:80'
volumes:
    mongodbdata:
        driver: local