# Generated by Django 2.2.3 on 2020-08-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                ("id", models.CharField(max_length=1000)),
                (
                    "index",
                    models.CharField(
                        max_length=1000, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
    ]
