# pull official base image
FROM python:3.7.8-alpine

# set work directory
WORKDIR /backend

# set temporary environment variables
ENV DJANGO_SECRET_KEY hello_from_linked_commons

# install dependencies
RUN pip install --upgrade pip
COPY ./src/requirements.txt .
RUN pip install -r ./requirements.txt

# copy project
COPY . ./

# Building Shelve dB
RUN ./entrypoint.sh