# Generated by Django 2.2.3 on 2020-07-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='provider_domain',
            new_name='index',
        ),
    ]
